JOORSAND/src/objects/Round_robin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>day_week__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Day of the week</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>start_time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>time_day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Times of day</label>
        <type>Checkbox</type>
    </fields>
    <label>Round Robin</label>
</CustomObject>

JOORSAND/src/classes/RoundRobinUpdateTest.cls
/**
 * Created by Valera on 30.01.2018.
 */

@IsTest
private class RoundRobinUpdateTest {

    public static void addTestRoundRobin() {
        Round_robin__c robin = new Round_robin__c(Name = 'TestRobin'
        , day_week__c = true
        , end_time__c = System.now().addMinutes(30)
        , is_active__c = true
        , start_time__c = System.now().addMinutes(-30)
        , time_day__c = true);
        insert robin;
        robin = new Round_robin__c(Name = 'Test2'
        , day_week__c = true
        , is_active__c = true
        , start_time__c = System.now().addMinutes(-30)
        , time_day__c = true);
        insert robin;
        System.debug(robin);
    }

    static testMethod void setTrueFlagDay() {
        addTestRoundRobin();
        Test.StartTest();
        ID batchprocessid = Database.executeBatch(new RoundRobinUpdate());
        Test.StopTest();
    }

    static testMethod void setFalseFlagDay() {
        addTestRoundRobin();
        Round_robin__c test = Round_robin__c.getInstance('TestRobin');
        test.end_time__c = System.now().addMinutes(-10);
        upsert test;
        System.Test.StartTest();
        ID batchprocessid = Database.executeBatch(new RoundRobinUpdate());
        System.Test.StopTest();
    }
}